### ISSUE TITLE
Move the Alexa API to a standalone pip module.

### ISSUE THREAD

**Issue by keatontaylor** [keatontaylor/custom_components#14]

**Comment by keatontaylor** [comment]
I considered this but am fairly confident that adding a TTS component where all it does is simply relay the text from the text box to our comment wouldn't be approved. An alternative would be to enhance the TTS components so that along with the mp4 of the text it includes the text of the message as well.

**Comment by alandtse** [comment]
My take is the TTS component in HA takes a string and will then generate a media file (I actually never verified it was mp4) to provide to a media player.  I think the TTS component for Alexa would do it with the limitation that it only works with Alexa media players.  I do think it's not consistent with the HA paradigm to have the tts as a service to a media player like we have now.

That said, the text inclusion option seems like it'd solve the problem but I wonder how prevalent the issue is where media_players can't play media files but can play text.

**Comment by dreimer1986** [comment]
Oooh, I feel mentioned ^^ Anyways. Yes, I use my Echoes on a german account. First I tried changing the doamin to de and thats it. Result was a Captcha loop. Then ppl on Discord said that .com should be working too. Well... sort of. My devices showed up but all as disconnected. Then I changed the code of the script as mentioned above aka changed accepted languages to de-DE, de and then it worked flawless. I did not try your new version yet. Will do asap.

**Comment by keatontaylor** [comment]
@dreimer1986 please let me know how it works with the new component. I would strongly prefer not to create logic that tries to interpret where the user account is located if it isn't necessary.

**Comment by kwdavidson** [comment]
Drop down to your configuration directory and delete the `alexa_media.pickle` file.

**Comment by alandtse** [comment]
@keatontaylor admittedly I haven't been active recently but part of the reason was I didn't want to impact the code while you performed this migration. Any thoughts on timeline?

**Comment by keatontaylor** [comment]
@alandtse very sorry for the delay, work has been pretty busy but I'll be sure to get this sorted this weekend. Ideally I want to move the base component to gitlab so I can take advantage of the CI stuff they have for free. The component seems fairly stable assuming it can get past code-review for HA.
