### ISSUE TITLE
Convert into a HA platform

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#62]
Per comments in #60 (which could be a sensor) and #56 (which is odd for HA), we should start moving the component into a platform that will spawn all the components.

#51 also would be a good addition.

**Comment by alandtse** [comment]
I can work on the main platform to launch the components along with the login. Do you have time to handle the API migration? I know you've been busy. I could take a shot but I haven't done any pypi publishing before. I know you started on it so I may need collaborator access to push versions if I help there.

**Comment by brianhanifin** [comment]
I think this makes a lot of sense! Potentially this could be an official component. Here are a few thoughts on the presentation of the user facing components. Feel free to ignore everything below. 😁 

### Alexa Media Player Controls
The original feature.... which I personally have never used. 🤷‍♂️

### Alexa Notifications
Interestingly the [Mycroft component](https://www.home-assistant.io/components/mycroft/) speech component falls under the Notifications category instead of Text-to-speech. It could be called `Alexa Text-to-speech`, but that could get confusing with Alexa Polly in the same category.

### Alexa Flash Briefing
Would the Flash Briefing feature be part of the Notifications component? I'm not sure what Home Assistant category that would fit in... there is an Other category.

### Alexa Sensor
I could see the Alexa sensor optionally reporting back more than just the entity_id of the last_alexa. There is more information in that Activities API response such as: last_phrase (last thing said to Alexa), the registered_customer_id (in case that would be useful), time_requested (in case someone would want to see if the request is current or stale possibly). It could be configurable for which values to expose, like the [Dark Sky Sensor](https://www.home-assistant.io/components/sensor.darksky/)'s monitored_conditions.

**Comment by alandtse** [comment]
I think anything related to playing programming is probably a media_player component. 

Notification is for sending messages to users.  TTS probably should be in the TTS category although it's much more limited than a standard TTS which generates an audio file that can be passed to any media_player (except for Alexa).

**Comment by alandtse** [comment]
In reviewing this more, I think TTS should probably be a notification component to avoid confusion.  This probably means we should deprecate TTS as a service since I'm not aware of any other component doing something similar.

We're also running into a potential name collision issue with the existing [Alexa component](https://www.home-assistant.io/components/alexa/).

So to recap:
Platform - Login and device discovery. I think it should also handle all refreshing so there's only one thread hitting Amazon's apis.
Media Player - Media player and services to interact with an Echo
Notification - Alexa TTS
Sensor - Last Alexa + Activities API. Also could have the lists which may be a Calendar component. 
Switch - Settings like Do Not Disturb, etc.

There are other parts of the Alexa App we can probably expose like timers/lists.

**Comment by brianhanifin** [comment]
How would this component be differentiated? Echo, Alexa_Echo, Alexa API, Alexa Devices?

Of course this wouldn't be the first component with alternate versions.... Although, my go to example Luton which had 3 hub components, now appear to be merged into one. The local and PLM modules are now depreciated.

This is a seemingly crazy thought... Have you looked at whether this should be a separate component? Is there a way to add these features into the existing component?

**Comment by alandtse** [comment]
@brianhanifin I think we may want to combine it so there isn't a name collision, but we should discuss that after we get the platform working.  

@keatontaylor regarding the AlexaPy library, in the AlexaAPI class: Architecturally why do we construct an AlexaAPI object using a session object and url instead of a AlexaLogin object?  In theory, AlexaLogin has both.  The issue is, both variables are private. 

For the platform separation work, it looks like HA can only pass around the objects and their public variables.  I think I'll either have to expose that private variable or just have the AlexaAPI handle AlexaLogin objects directly, but I want to make sure I'm not breaking something you had in mind.

**Comment by alandtse** [comment]
FYI, updated the Wiki documentation to explain the breaking changes on [configuration](https://github.com/keatontaylor/custom_components/wiki/Configuration#versions--100). I also broke out the API in [this alexapy branch](https://github.com/alandtse/custom_components/tree/alexapy) which is more advanced than my platform branch.

@keatontaylor I updated my version of alexapy on gitlab. Do you want me to have contrib access on gitlab/pypi? I'm ok with you having final approval since this is your baby that I've apparently hijacked. ;) Or if you want me to active maintain it too I can do that.
