### ISSUE TITLE
Captcha requested continuusly

### ISSUE THREAD

**Issue by antoweb** [keatontaylor/custom_components#873]
**Describe the bug**

**To Reproduce**
1. open hassio
2. See notfication
3. Notification authentication is present
4. Insert captcha

**Expected behavior**
I need to authenticate just first time not every 10/15 mins

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by skynet01** [comment]
@alandtse I still have this issue and i did not reset the password. I have the following in the error log:

`alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xa301e100>,), {'data': {'password': 'REDACTED 14 CHARS', 'captcha': 'afxxbw'}}): An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'URL' object has no attribute 'decode'",)`

I also have tried removing the integration from the config and activating it from the beginning of the UI (i also don't have 2fa enabled). 
It seems the issue is triggered because amazon sends a text to my cell phone about allowing access (you have to click a link then press approve button) and this is probably why the login fails.

"Amazon security alert. Tap link to respond: https://amazon.com/a/c/r?k=3543871c62084f9ebfd3708e3e804411-8dc5"

**Comment by alandtse** [comment]
Please respond in the live ticket #870 and if you can provide your debug logs we may be able to fix it.

**Comment by alandtse** [comment]
Nevermind, respond in #880
